# Generated by Django 3.2.6 on 2021-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211112_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_type',
            field=models.CharField(blank=True, choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True, verbose_name='release_type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(max_length=500, verbose_name='Trailer_Link'),
        ),
    ]
