# Generated by Django 3.2.6 on 2021-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211222_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
